name: 'Deploy to NPM with oddish'
branding:
  icon: 'package'
  color: 'red'
description: 'Deploy your NPM package using oddish directly from GitHub'
runs:
  using: 'node12'
  main: 'oddish.js'
inputs:
  npmToken:
    description: "Your NPM Token"
    required: true